import type { FluidSpecSheet, VehicleSpecs } from "@/lib/types";

interface CatalogEntry {
  make: string;
  modelIncludes: string[];
  yearFrom: number;
  yearTo: number;
  oilViscosity: string;
  oilSpec: string;
  oilCapacityQt: string;
  coolant: string;
  transmissionFluid: string;
  brakeFluid: string;
  tirePsiFront: string;
  tirePsiRear: string;
  oilFilterSku: string;
  airFilterSku: string;
  cabinFilterSku: string;
  sparkPlugGap: string;
  notes: string[];
}

const CATALOG: CatalogEntry[] = [
  {
    make: "HONDA",
    modelIncludes: ["ACCORD"],
    yearFrom: 2003,
    yearTo: 2007,
    oilViscosity: "5W-20",
    oilSpec: "API SN / ILSAC GF-5, Honda Genuine",
    oilCapacityQt: "4.5 qt with filter",
    coolant: "Honda Type 2 blue, ~1.5 gal system",
    transmissionFluid: "Honda ATF-Z1 / DW-1 (do not use generic ATF)",
    brakeFluid: "DOT 3",
    tirePsiFront: "32 PSI",
    tirePsiRear: "32 PSI",
    oilFilterSku: "Honda 15400-PLM-A02 / Fram PH7317",
    airFilterSku: "Honda 17220-RAA-A00",
    cabinFilterSku: "Honda 80292-SDA-A01",
    sparkPlugGap: "0.044 in (1.1 mm) — iridium, do not re-gap",
    notes: ["Cabin filter is behind the glove box and is a 5-minute DIY."],
  },
  {
    make: "HONDA",
    modelIncludes: ["CIVIC"],
    yearFrom: 2016,
    yearTo: 2021,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Honda Genuine",
    oilCapacityQt: "3.7 qt with filter (1.5T) / 4.4 qt (2.0)",
    coolant: "Honda Type 2 blue",
    transmissionFluid: "HCF-2 (CVT) or Honda DW-1 (auto)",
    brakeFluid: "DOT 3",
    tirePsiFront: "32 PSI",
    tirePsiRear: "32 PSI",
    oilFilterSku: "Honda 15400-RTA-003",
    airFilterSku: "Honda 17220-5BA-A00",
    cabinFilterSku: "Honda 80292-TBA-A01",
    sparkPlugGap: "0.043 in (1.1 mm)",
    notes: ["Confirm 1.5T vs 2.0 on the under-hood emissions label."],
  },
  {
    make: "FORD",
    modelIncludes: ["F-150", "F150"],
    yearFrom: 2011,
    yearTo: 2014,
    oilViscosity: "5W-20",
    oilSpec: "API SN, Ford WSS-M2C945-A",
    oilCapacityQt: "6.0 qt (3.5 EcoBoost) / 8.0 qt (5.0 V8) with filter",
    coolant: "Motorcraft Orange / Motorcraft Yellow — do not mix",
    transmissionFluid: "Mercon LV",
    brakeFluid: "DOT 4",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Motorcraft FL-500-S",
    airFilterSku: "Motorcraft FA-1883",
    cabinFilterSku: "Motorcraft FP-71",
    sparkPlugGap: "0.033–0.037 in (EcoBoost); 0.052–0.056 in (5.0)",
    notes: ["Door-jamb sticker is the legal tire-pressure spec, not the sidewall max."],
  },
  {
    make: "TOYOTA",
    modelIncludes: ["CAMRY"],
    yearFrom: 2018,
    yearTo: 2024,
    oilViscosity: "0W-16",
    oilSpec: "API SP / ILSAC GF-6B, Toyota Genuine",
    oilCapacityQt: "4.8 qt with filter (2.5 A25A)",
    coolant: "Toyota Super Long Life (pink), 50/50",
    transmissionFluid: "Toyota ATF WS",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Toyota 04152-YZZA6",
    airFilterSku: "Toyota 17801-0T021",
    cabinFilterSku: "Toyota 87139-YZZ08",
    sparkPlugGap: "0.044 in — Denso iridium, do not re-gap",
    notes: ["0W-16 is specified; 0W-20 is an acceptable emergency fill on some years."],
  },
  {
    make: "TESLA",
    modelIncludes: ["MODEL S", "MODELS"],
    yearFrom: 2012,
    yearTo: 2026,
    oilViscosity: "Not applicable",
    oilSpec: "Battery EV — no engine oil",
    oilCapacityQt: "—",
    coolant: "Tesla glycol coolant, battery/drive-unit loop",
    transmissionFluid: "Drive-unit fluid — service interval per Tesla",
    brakeFluid: "DOT 3 (some years DOT 4)",
    tirePsiFront: "42 PSI (confirm door sticker)",
    tirePsiRear: "42 PSI (confirm door sticker)",
    oilFilterSku: "—",
    airFilterSku: "Tesla cabin HEPA / pollen filter",
    cabinFilterSku: "Tesla 1069171-00-E (varies by refresh)",
    sparkPlugGap: "—",
    notes: ["A shop quoting an oil change on this VIN is either looking at the wrong car or upselling fiction."],
  },
  {
    make: "HONDA",
    modelIncludes: ["CR-V", "CRV"],
    yearFrom: 2017,
    yearTo: 2022,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Honda Genuine",
    oilCapacityQt: "3.7 qt with filter (1.5T)",
    coolant: "Honda Type 2 blue",
    transmissionFluid: "HCF-2 (CVT) — do not use generic ATF",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Honda 15400-RTA-003",
    airFilterSku: "Honda 17220-5BA-A00",
    cabinFilterSku: "Honda 80292-TBA-A01",
    sparkPlugGap: "0.043 in",
    notes: ["CVT fluid is HCF-2 only. A 'transmission flush' with Dexron is a damage path, not a service."],
  },
  {
    make: "HONDA",
    modelIncludes: ["CIVIC"],
    yearFrom: 2022,
    yearTo: 2026,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Honda Genuine",
    oilCapacityQt: "3.7–4.4 qt with filter — confirm 1.5T vs 2.0 on the label",
    coolant: "Honda Type 2 blue",
    transmissionFluid: "HCF-2 (CVT) or Honda DW-1",
    brakeFluid: "DOT 3",
    tirePsiFront: "32 PSI",
    tirePsiRear: "32 PSI",
    oilFilterSku: "Honda 15400-RTA-003",
    airFilterSku: "Honda 17220-5BA-A00",
    cabinFilterSku: "Honda 80292-TBA-A01",
    sparkPlugGap: "0.043 in",
    notes: ["11th-gen Civic: confirm turbo vs 2.0 on the under-hood emissions label."],
  },
  {
    make: "HONDA",
    modelIncludes: ["ACCORD"],
    yearFrom: 2018,
    yearTo: 2022,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Honda Genuine",
    oilCapacityQt: "3.7 qt (1.5T) / 4.8 qt (2.0T) with filter",
    coolant: "Honda Type 2 blue",
    transmissionFluid: "HCF-2 (CVT, 1.5T) or ATF DW-1 (10-speed, 2.0T)",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Honda 15400-RTA-003",
    airFilterSku: "Honda 17220-6A0-A00",
    cabinFilterSku: "Honda 80292-TVA-A01",
    sparkPlugGap: "0.043 in",
    notes: ["10-speed vs CVT changes the fluid. Read the under-hood label before you buy ATF."],
  },
  {
    make: "HONDA",
    modelIncludes: ["ODYSSEY"],
    yearFrom: 2018,
    yearTo: 2025,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Honda Genuine",
    oilCapacityQt: "5.7 qt with filter (3.5 V6)",
    coolant: "Honda Type 2 blue",
    transmissionFluid: "Honda ATF DW-1 (9- or 10-speed — confirm)",
    brakeFluid: "DOT 3",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Honda 15400-RTA-003",
    airFilterSku: "Honda 17220-5J6-A00",
    cabinFilterSku: "Honda 80292-THR-A11",
    sparkPlugGap: "0.043 in — iridium, do not re-gap",
    notes: ["Rear cabin filter is a second SKU on some years — check both glove-box and console."],
  },
  {
    make: "TOYOTA",
    modelIncludes: ["COROLLA"],
    yearFrom: 2019,
    yearTo: 2026,
    oilViscosity: "0W-16",
    oilSpec: "API SP / ILSAC GF-6B, Toyota Genuine",
    oilCapacityQt: "4.4 qt with filter (2.0 M20A)",
    coolant: "Toyota Super Long Life (pink), 50/50",
    transmissionFluid: "Toyota CVT FE or ATF WS — confirm trans",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Toyota 04152-YZZA6",
    airFilterSku: "Toyota 17801-0T020",
    cabinFilterSku: "Toyota 87139-YZZ08",
    sparkPlugGap: "0.044 in — do not re-gap",
    notes: ["0W-16 is on the cap. 0W-20 is an emergency fill on some years, not the spec."],
  },
  {
    make: "TOYOTA",
    modelIncludes: ["RAV4"],
    yearFrom: 2019,
    yearTo: 2026,
    oilViscosity: "0W-16",
    oilSpec: "API SP / ILSAC GF-6B, Toyota Genuine",
    oilCapacityQt: "4.8 qt with filter (2.5 A25A)",
    coolant: "Toyota Super Long Life (pink), 50/50",
    transmissionFluid: "Toyota ATF WS",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Toyota 04152-YZZA6",
    airFilterSku: "Toyota 17801-F4010",
    cabinFilterSku: "Toyota 87139-07820",
    sparkPlugGap: "0.044 in",
    notes: ["Hybrid models still use engine oil — the 0W-16 spec still applies to the 2.5."],
  },
  {
    make: "TOYOTA",
    modelIncludes: ["TACOMA"],
    yearFrom: 2016,
    yearTo: 2023,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Toyota Genuine",
    oilCapacityQt: "6.1 qt (3.5 V6) / 4.6 qt (2.7) with filter",
    coolant: "Toyota Super Long Life (pink), 50/50",
    transmissionFluid: "Toyota ATF WS",
    brakeFluid: "DOT 3",
    tirePsiFront: "30 PSI (confirm door sticker — bed load changes this)",
    tirePsiRear: "30 PSI",
    oilFilterSku: "Toyota 04152-YZZA1",
    airFilterSku: "Toyota 17801-0P050",
    cabinFilterSku: "Toyota 87139-YZZ08",
    sparkPlugGap: "0.044 in",
    notes: ["Door sticker wins over the sidewall, especially if you add a camper or load."],
  },
  {
    make: "FORD",
    modelIncludes: ["ESCAPE"],
    yearFrom: 2013,
    yearTo: 2019,
    oilViscosity: "5W-20",
    oilSpec: "API SN, Ford WSS-M2C945-A",
    oilCapacityQt: "5.7 qt (1.6/2.0 EcoBoost) with filter",
    coolant: "Motorcraft Orange / Yellow — do not mix",
    transmissionFluid: "Mercon LV",
    brakeFluid: "DOT 4",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Motorcraft FL-910-S",
    airFilterSku: "Motorcraft FA-1912",
    cabinFilterSku: "Motorcraft FP-71",
    sparkPlugGap: "0.030–0.033 in (EcoBoost)",
    notes: ["EcoBoost oil-change interval is not a suggestion if you tow or do short trips."],
  },
  {
    make: "FORD",
    modelIncludes: ["F-150", "F150"],
    yearFrom: 2015,
    yearTo: 2020,
    oilViscosity: "5W-30",
    oilSpec: "API SN Plus / SP, Ford WSS-M2C946-A / 961-A",
    oilCapacityQt: "6.0 qt (2.7/3.5 EcoBoost) / 8.8 qt (5.0) with filter",
    coolant: "Motorcraft Orange or Yellow — confirm the cap",
    transmissionFluid: "Mercon LV",
    brakeFluid: "DOT 4",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Motorcraft FL-500-S",
    airFilterSku: "Motorcraft FA-1883",
    cabinFilterSku: "Motorcraft FP-68",
    sparkPlugGap: "0.030–0.033 in (EcoBoost); 0.049–0.053 in (5.0)",
    notes: ["Confirm 2.7 vs 3.5 vs 5.0 before you buy oil volume. The door sticker still owns tire PSI."],
  },
  {
    make: "CHEVROLET",
    modelIncludes: ["SILVERADO"],
    yearFrom: 2014,
    yearTo: 2018,
    oilViscosity: "0W-20",
    oilSpec: "API SN, GM dexos1 Gen 2",
    oilCapacityQt: "8.0 qt with filter (5.3 V8)",
    coolant: "GM Dex-Cool (orange)",
    transmissionFluid: "Dexron VI",
    brakeFluid: "DOT 3",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "ACDelco PF63 / PF63E",
    airFilterSku: "ACDelco A3239C",
    cabinFilterSku: "ACDelco CF188",
    sparkPlugGap: "0.040 in (5.3)",
    notes: ["AFM/DFM lifter noise is a diagnosis, not an automatic 'needs a new engine' on the first visit."],
  },
  {
    make: "CHEVROLET",
    modelIncludes: ["EQUINOX"],
    yearFrom: 2018,
    yearTo: 2024,
    oilViscosity: "0W-20",
    oilSpec: "API SP, GM dexos1 Gen 3",
    oilCapacityQt: "5.3 qt with filter (1.5T)",
    coolant: "GM Dex-Cool (orange)",
    transmissionFluid: "Dexron VI / GM CVT fluid — confirm",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "ACDelco PF66",
    airFilterSku: "ACDelco A3245C",
    cabinFilterSku: "ACDelco CF3258",
    sparkPlugGap: "0.026–0.030 in (1.5T)",
    notes: ["1.5T vs 2.0T changes capacity and plug gap. Read the under-hood label."],
  },
  {
    make: "RAM",
    modelIncludes: ["1500"],
    yearFrom: 2013,
    yearTo: 2018,
    oilViscosity: "5W-20",
    oilSpec: "API SN, FCA 04184531AD / MS-6395",
    oilCapacityQt: "7.0 qt with filter (5.7 Hemi)",
    coolant: "Mopar orange 50/50 (OAT) — do not mix with green",
    transmissionFluid: "Mopar ATF+4",
    brakeFluid: "DOT 3",
    tirePsiFront: "35 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Mopar 04884899AB / Mopar 68191349AA",
    airFilterSku: "Mopar 53034054AB",
    cabinFilterSku: "Mopar 68038796AA",
    sparkPlugGap: "0.043 in (5.7)",
    notes: ["ATF+4 is not Dexron. A 'universal ATF' in an 8-speed or 65RFE is how you buy a valve body."],
  },
  {
    make: "JEEP",
    modelIncludes: ["WRANGLER"],
    yearFrom: 2018,
    yearTo: 2024,
    oilViscosity: "0W-20",
    oilSpec: "API SP, FCA MS-13340 / dexos1",
    oilCapacityQt: "5.0 qt (2.0T) / 5.9 qt (3.6) with filter",
    coolant: "Mopar orange 50/50",
    transmissionFluid: "Mopar 8 & 9 Speed ATF or manual Mopar MS-12974 — confirm",
    brakeFluid: "DOT 3",
    tirePsiFront: "Door sticker — lifts and 35s change this",
    tirePsiRear: "Door sticker",
    oilFilterSku: "Mopar 68191349AA",
    airFilterSku: "Mopar 68232852AB",
    cabinFilterSku: "Mopar 68225653AA",
    sparkPlugGap: "0.043 in (3.6); 0.031 in (2.0T)",
    notes: ["Aftermarket lifts do not rewrite the door-sticker PSI. Measure, don't copy the sidewall."],
  },
  {
    make: "SUBARU",
    modelIncludes: ["OUTBACK"],
    yearFrom: 2015,
    yearTo: 2019,
    oilViscosity: "0W-20",
    oilSpec: "API SN, Subaru Genuine",
    oilCapacityQt: "5.1 qt with filter (2.5)",
    coolant: "Subaru Super Coolant (blue)",
    transmissionFluid: "Subaru CVT fluid (TR580) — not generic ATF",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "32 PSI",
    oilFilterSku: "Subaru 15208AA15A",
    airFilterSku: "Subaru 16546AA12A",
    cabinFilterSku: "Subaru 72880FJ000",
    sparkPlugGap: "0.031 in",
    notes: ["CVT fluid is a Subaru SKU. A 'flush special' with Dexron is how these boxes die early."],
  },
  {
    make: "SUBARU",
    modelIncludes: ["FORESTER"],
    yearFrom: 2014,
    yearTo: 2018,
    oilViscosity: "0W-20",
    oilSpec: "API SN, Subaru Genuine",
    oilCapacityQt: "5.1 qt with filter (2.5)",
    coolant: "Subaru Super Coolant (blue)",
    transmissionFluid: "Subaru CVT fluid — not generic ATF",
    brakeFluid: "DOT 3",
    tirePsiFront: "32 PSI",
    tirePsiRear: "30 PSI",
    oilFilterSku: "Subaru 15208AA15A",
    airFilterSku: "Subaru 16546AA09A",
    cabinFilterSku: "Subaru 72880FG000",
    sparkPlugGap: "0.031 in",
    notes: ["Confirm 2.0 turbo vs 2.5 NA — turbo years often specify 5W-30."],
  },
  {
    make: "MAZDA",
    modelIncludes: ["CX-5", "CX5"],
    yearFrom: 2017,
    yearTo: 2024,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Mazda Genuine",
    oilCapacityQt: "4.8 qt with filter (2.5)",
    coolant: "Mazda FL22 (green) 50/50",
    transmissionFluid: "Mazda ATF FZ",
    brakeFluid: "DOT 3",
    tirePsiFront: "36 PSI",
    tirePsiRear: "35 PSI",
    oilFilterSku: "Mazda PY01-14-302 / 1WPE-14-302",
    airFilterSku: "Mazda PY8W-13-Z40",
    cabinFilterSku: "Mazda KD45-61-J6X",
    sparkPlugGap: "0.028–0.031 in (2.5T); 0.051 in (NA — confirm)",
    notes: ["Skyactiv-G vs Skyactiv-T changes plug gap. Read the under-hood label."],
  },
  {
    make: "HYUNDAI",
    modelIncludes: ["ELANTRA"],
    yearFrom: 2017,
    yearTo: 2020,
    oilViscosity: "5W-20",
    oilSpec: "API SN / ILSAC GF-5, Hyundai Genuine",
    oilCapacityQt: "4.2 qt with filter (2.0)",
    coolant: "Hyundai Phosphate-based (green) 50/50 — not Dex-Cool",
    transmissionFluid: "Hyundai SP-IV",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Hyundai 26300-35504",
    airFilterSku: "Hyundai 28113-F2000",
    cabinFilterSku: "Hyundai 97133-F2000",
    sparkPlugGap: "0.044 in",
    notes: ["Hyundai/Kia engines in this era have TSB and campaign history — check /recalls before a bottom-end quote."],
  },
  {
    make: "KIA",
    modelIncludes: ["SOUL"],
    yearFrom: 2014,
    yearTo: 2019,
    oilViscosity: "5W-20",
    oilSpec: "API SN, Kia Genuine",
    oilCapacityQt: "4.2 qt with filter (2.0)",
    coolant: "Kia phosphate coolant 50/50 — not Dex-Cool",
    transmissionFluid: "Kia SP-IV",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Kia 26300-35503",
    airFilterSku: "Kia 28113-B2000",
    cabinFilterSku: "Kia 97133-B2000",
    sparkPlugGap: "0.044 in",
    notes: ["Check open campaigns on this VIN before you authorize engine work."],
  },
  {
    make: "NISSAN",
    modelIncludes: ["ROGUE"],
    yearFrom: 2014,
    yearTo: 2020,
    oilViscosity: "0W-20",
    oilSpec: "API SN, Nissan Genuine",
    oilCapacityQt: "4.9 qt with filter (2.5)",
    coolant: "Nissan blue Long Life 50/50",
    transmissionFluid: "Nissan NS-3 CVT fluid — not generic ATF",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Nissan 15208-9E000",
    airFilterSku: "Nissan 16546-4BA1A",
    cabinFilterSku: "Nissan 27277-4BA0A",
    sparkPlugGap: "0.044 in",
    notes: ["NS-3 only in the CVT. A 'flush special' with Dexron is a known way to kill these units."],
  },
  {
    make: "VOLKSWAGEN",
    modelIncludes: ["JETTA"],
    yearFrom: 2011,
    yearTo: 2018,
    oilViscosity: "5W-40",
    oilSpec: "VW 502 00 / 505 00 (or 504 00/507 00 if the cap says so)",
    oilCapacityQt: "5.7 qt with filter (1.8 TSI) / 4.6 qt (2.0 TDI)",
    coolant: "VW G13 / G12++ (purple/pink) — not green universal",
    transmissionFluid: "VW G 052 182 (DSG) or 09G ATF — confirm gearbox",
    brakeFluid: "DOT 4",
    tirePsiFront: "35 PSI",
    tirePsiRear: "32 PSI",
    oilFilterSku: "VW 06K 115 466 / Mann W 712/95",
    airFilterSku: "VW 6R0 129 620 C",
    cabinFilterSku: "VW 1K0 819 644 B",
    sparkPlugGap: "0.024–0.028 in (TSI)",
    notes: ["The oil spec is a VW number, not a viscosity alone. '5W-40 Euro' still has to list 502 00."],
  },
  {
    make: "BMW",
    modelIncludes: ["328", "330", "3 SERIES", "3-SERIES"],
    yearFrom: 2012,
    yearTo: 2018,
    oilViscosity: "0W-20 or 0W-30",
    oilSpec: "BMW Longlife-01 FE / LL-14 FE+ — confirm the cap",
    oilCapacityQt: "5.3 qt with filter (N20 / B46)",
    coolant: "BMW HT-12 (blue) or lifetime blue — no green universal",
    transmissionFluid: "ZF Lifeguard 8 (8HP) — not Dexron",
    brakeFluid: "DOT 4",
    tirePsiFront: "Door sticker (often 32–35 PSI, run-flat dependent)",
    tirePsiRear: "Door sticker",
    oilFilterSku: "BMW 11 42 7 566 327 / Mann HU 816 x",
    airFilterSku: "BMW 13 71 7 595 941",
    cabinFilterSku: "BMW 64 31 9 378 425",
    sparkPlugGap: "OEM NGK / Bosch — do not re-gap",
    notes: ["An independent who knows BMW is cheaper than the dealer; a generic lube shop is how you get the wrong LL spec."],
  },
  {
    make: "LEXUS",
    modelIncludes: ["RX"],
    yearFrom: 2016,
    yearTo: 2022,
    oilViscosity: "0W-20",
    oilSpec: "API SP / ILSAC GF-6, Toyota/Lexus Genuine",
    oilCapacityQt: "4.8 qt (2.0T) / 6.4 qt (3.5 V6) with filter",
    coolant: "Toyota Super Long Life (pink), 50/50",
    transmissionFluid: "Toyota ATF WS",
    brakeFluid: "DOT 3",
    tirePsiFront: "33 PSI",
    tirePsiRear: "33 PSI",
    oilFilterSku: "Toyota 04152-YZZA1",
    airFilterSku: "Toyota 17801-31120",
    cabinFilterSku: "Toyota 87139-50100",
    sparkPlugGap: "0.044 in",
    notes: ["Hybrid RX still needs engine oil on the 2.5/3.5 schedule — there is no 'EV oil skip.'"],
  },
];

function yearOf(specs: VehicleSpecs): number {
  const parsed = Number.parseInt(specs.year, 10);
  return Number.isFinite(parsed) ? parsed : 0;
}

function matchCatalog(specs: VehicleSpecs): CatalogEntry | undefined {
  const year = yearOf(specs);
  const make = specs.make.toUpperCase();
  const model = specs.model.toUpperCase();
  return CATALOG.find(
    (entry) =>
      entry.make === make &&
      year >= entry.yearFrom &&
      year <= entry.yearTo &&
      entry.modelIncludes.some((token) => model.includes(token)),
  );
}

function heuristicSheet(specs: VehicleSpecs): FluidSpecSheet {
  const year = yearOf(specs);
  const liters = Number.parseFloat(specs.engineDisplacement);
  const fuel = specs.fuelType.toLowerCase();
  const isEv = fuel.includes("electric") || specs.make.toUpperCase() === "TESLA";
  const isDiesel = fuel.includes("diesel");
  const isTruck = /truck|pickup|suv|mpv/i.test(specs.bodyClass);

  if (isEv) {
    return {
      oilViscosity: "Not applicable",
      oilSpec: "Battery EV — no engine oil",
      oilCapacityQt: "—",
      coolant: "OEM battery / inverter coolant only",
      transmissionFluid: "Drive-unit fluid per OEM",
      brakeFluid: "DOT 3 or DOT 4 — confirm cap",
      tirePsiFront: "Door-jamb sticker (often 42–45 PSI)",
      tirePsiRear: "Door-jamb sticker (often 42–45 PSI)",
      oilFilterSku: "—",
      airFilterSku: "Cabin / HEPA filter only",
      cabinFilterSku: "OEM cabin filter",
      sparkPlugGap: "—",
      source: "heuristic",
      caveats: ["No engine oil, plugs, or oil filter exist on this powertrain."],
    };
  }

  let oilViscosity = "5W-30";
  if (isDiesel) oilViscosity = year >= 2017 ? "5W-40" : "15W-40";
  else if (year >= 2018 && liters > 0 && liters <= 2.5) oilViscosity = "0W-20";
  else if (year >= 2011) oilViscosity = "5W-20";

  const oilCapacityQt =
    liters >= 5 ? "7.0–8.0 qt typical V8" : liters >= 3 ? "5.5–6.5 qt typical V6" : "4.4–5.0 qt typical I4";

  return {
    oilViscosity: `${oilViscosity} Synthetic`,
    oilSpec: isDiesel ? "API CK-4 diesel" : "API SP / ILSAC GF-6",
    oilCapacityQt,
    coolant: "OEM-specified 50/50 — color is not a spec",
    transmissionFluid: specs.transmission || "OEM-only ATF / CVT fluid",
    brakeFluid: year >= 2015 ? "DOT 4" : "DOT 3",
    tirePsiFront: isTruck ? "35 PSI" : "32 PSI",
    tirePsiRear: isTruck ? "35 PSI" : "32 PSI",
    oilFilterSku: `Ask for OEM ${specs.make || "factory"} oil filter`,
    airFilterSku: `Ask for OEM ${specs.make || "factory"} air filter`,
    cabinFilterSku: `Ask for OEM ${specs.make || "factory"} cabin filter`,
    sparkPlugGap: "Confirm on the under-hood emissions label",
    source: "heuristic",
    caveats: [
      "Exact viscosity and capacity live on the under-hood label and owner's manual — this is a factory-typical starting point, not a substitute for the door-jamb sticker.",
    ],
  };
}

export function buildFluidSpecSheet(specs: VehicleSpecs): FluidSpecSheet {
  const hit = matchCatalog(specs);
  if (!hit) return heuristicSheet(specs);

  return {
    oilViscosity: hit.oilViscosity,
    oilSpec: hit.oilSpec,
    oilCapacityQt: hit.oilCapacityQt,
    coolant: hit.coolant,
    transmissionFluid: hit.transmissionFluid,
    brakeFluid: hit.brakeFluid,
    tirePsiFront: hit.tirePsiFront,
    tirePsiRear: hit.tirePsiRear,
    oilFilterSku: hit.oilFilterSku,
    airFilterSku: hit.airFilterSku,
    cabinFilterSku: hit.cabinFilterSku,
    sparkPlugGap: hit.sparkPlugGap,
    source: "catalog",
    caveats: hit.notes,
  };
}
