import type { RoTerm } from "@/lib/jobs/types";

export const RO_TERMS: RoTerm[] = [
  {
    slug: "lof",
    term: "LOF",
    also: ["lube oil filter", "oil change"],
    means: "Lube, oil, and filter. Drain the sump, new filter, refill to the spec on the cap.",
    sayToOwner: "Oil and filter. Ask which viscosity and whether they used the spec on the cap, not 'whatever was on sale.'",
    trap: "LOF is not a 'full service' and not a license to add a flush, an induction, or a cabin filter without a price.",
    group: "service",
  },
  {
    slug: "mpi",
    term: "MPI / multi-point",
    also: ["multipoint", "courtesy inspection", "21-point", "30-point"],
    means: "A walk-around the shop uses to find more work. Useful when it writes measurements. Sales when it writes 'due.'",
    sayToOwner: "I want the numbers: rotor mm, pad mm, tread 32nds, not 'brakes due.'",
    trap: "'Recommended' on an MPI is not a fail. Ask what is below spec today.",
    group: "service",
  },
  {
    slug: "alignment",
    term: "Alignment",
    also: ["four wheel alignment", "2-wheel", "thrust"],
    means: "Adjust toe (and camber/caster if the car has it) so the tires track straight.",
    sayToOwner: "Ask for the printout: before and after, in degrees. A 'lifetime alignment' is a coupon, not geometry.",
    trap: "An alignment will not fix a bent knuckle or a worn inner tie rod. Those are parts, then the alignment.",
    group: "steering",
  },
  {
    slug: "trans-service",
    term: "Trans service",
    also: ["transmission service", "drain and fill", "pan drop"],
    means: "Usually a drain and fill, sometimes a pan drop and filter. Not the same as a flush.",
    sayToOwner: "Ask: drain-and-fill or machine flush? Which fluid spec? Filter this time?",
    trap: "A flush on a high-mile untouched unit can be a gamble. Drain-and-fill is the conservative sentence.",
    group: "trans",
  },
  {
    slug: "flush",
    term: "Flush",
    also: ["power flush", "machine flush", "cooler flush"],
    means: "A machine pushes fluid through a system. Coolant, trans, brake, and power-steering flushes are different jobs.",
    sayToOwner: "Which system, and why a flush instead of a drain? Show me the contamination.",
    trap: "Flush packages are high-margin. Contamination or a spec interval is the reason; a menu board is not.",
    group: "service",
  },
  {
    slug: "rr",
    term: "R&R",
    also: ["remove and replace", "r and r"],
    means: "Remove and replace. They took it off and put a new (or reman) one on.",
    sayToOwner: "What was measured on the old part? Keep the old part.",
    trap: "R&R is not a diagnosis. It is the labor line after someone decided.",
    group: "ticket",
  },
  {
    slug: "ri",
    term: "R&I",
    also: ["remove and install", "r and i"],
    means: "Remove and install — often the same part, or a part they sent out (machine the rotor, rebuild the caliper).",
    sayToOwner: "Is this the same part coming back, or a new one?",
    trap: "R&I labor can hide a machine-shop sublet. Ask for that line.",
    group: "ticket",
  },
  {
    slug: "ntf",
    term: "NTF",
    also: ["could not duplicate", "cnd", "no trouble found", "verify concern"],
    means: "Could not duplicate. The tech did not see the complaint in the bay or on the road test.",
    sayToOwner: "That is an honest sentence. Pay the diagnosis if they road-tested and scanned. Do not pay a parts guess.",
    trap: "NTF plus a 'preventive' part is a parts cannon. Ask for the road-test notes.",
    group: "diag",
  },
  {
    slug: "shop-supplies",
    term: "Shop supplies",
    also: ["hazardous waste", "environmental", "shop materials"],
    means: "A percentage or flat fee for rags, solvents, waste oil. Legal in many states if disclosed.",
    sayToOwner: "How much, and is it a percent of labor or a flat? I want it on the written estimate.",
    trap: "A 10% 'supplies' on a $2,000 ticket is a junk fee unless they can show a policy. Ask to cap it.",
    group: "ticket",
  },
  {
    slug: "while-in-there",
    term: "While we're in there",
    also: ["while in there", "since we are here"],
    means: "Additional work discovered after teardown. Fair when they call with a price before they do it.",
    sayToOwner: "Call me with the new out-the-door number before you continue.",
    trap: "Unauthorized extras are how a $400 job becomes $1,400. Silence is not consent.",
    group: "ticket",
  },
  {
    slug: "customer-states",
    term: "Customer states",
    also: ["c/s", "cust states"],
    means: "The complaint as written on the RO. This is the job. Everything else is extra.",
    sayToOwner: "Read this line. If it is wrong, they will 'fix' the wrong car.",
    trap: "A vague 'check brakes' becomes an MPI upsell. Write the symptom: when, speed, noise.",
    group: "ticket",
  },
  {
    slug: "tech-rec",
    term: "Tech rec / advisor rec",
    also: ["recommended", "suggested", "due"],
    means: "A suggestion. Not a measurement. Not a legal fail unless they wrote the spec.",
    sayToOwner: "Recommended is not failed. What is the reading and what is the minimum?",
    trap: "'Pads at 4 mm, spec is 2 mm' is soon. 'Pads due' is a sales word.",
    group: "ticket",
  },
  {
    slug: "stored-pending",
    term: "Stored / pending / permanent",
    also: ["pending code", "permanent dtc", "history code"],
    means: "Stored = it happened. Pending = it almost confirmed. Permanent = it stays until the monitor passes, even if you clear.",
    sayToOwner: "Ask which. A pending EVAP after a loose cap is not a canister.",
    trap: "Clearing codes is not a repair. Permanent codes come back if the monitor fails.",
    group: "diag",
  },
  {
    slug: "relearn",
    term: "Relearn / adaptation",
    also: ["idle relearn", "throttle relearn", "tpms relearn"],
    means: "The computer must re-learn a stop or a sensor after a battery or a throttle cleaning.",
    sayToOwner: "If they cleaned the throttle, a relearn is part of the job — not a second ticket.",
    trap: "A new ETB quoted because nobody did the relearn is a common miss.",
    group: "diag",
  },
  {
    slug: "sublet",
    term: "Sublet",
    also: ["vendor", "machine shop", "tow"],
    means: "Work sent outside the shop. Alignment rack down the street, machine the rotors, tint, programming.",
    sayToOwner: "Who is doing it, and what is their line on my ticket?",
    trap: "Sublet plus a markup is normal. An unmarked sublet is how you lose the old part.",
    group: "ticket",
  },
  {
    slug: "comeback",
    term: "Comeback / goodwill",
    also: ["we-owe", "policy"],
    means: "They are fixing their own work, or eating a charge to keep you. Write the promise.",
    sayToOwner: "What is covered, for how long, and who authorized it?",
    trap: "Verbal goodwill evaporates at shift change. Get the RO number.",
    group: "ticket",
  },
  {
    slug: "pads-rotors",
    term: "Pads / rotors",
    also: ["brake job", "resurface", "machine rotors"],
    means: "Friction material and the iron discs. Thickness is in millimeters. Below minimum is a fail.",
    sayToOwner: "Write LF/RF/LR/RR in mm, and the hat minimum. 'They're due' is not a number.",
    trap: "Machining a rotor already at minimum is a comeback. Measure first.",
    group: "brakes",
  },
  {
    slug: "caliper",
    term: "Caliper",
    also: ["seized caliper", "slider"],
    means: "The clamp. Seized sliders or a stuck piston pull the car or eat a pad on one side.",
    sayToOwner: "Which corner, and did both pads wear even? Uneven wear is the caliper story.",
    trap: "A caliper on every brake job is a habit. One stuck corner is a part.",
    group: "brakes",
  },
  {
    slug: "brake-flush",
    term: "Brake fluid service",
    also: ["brake flush", "bleed"],
    means: "Hygroscopic fluid ages. A flush is interval or contamination — not automatically every oil change.",
    sayToOwner: "Test strip or boiling-point number, or the year-old interval in the book.",
    trap: "Menu-board brake flushes at every visit are a pitch. Copper/moisture test is a reason.",
    group: "brakes",
  },
  {
    slug: "strut",
    term: "Strut / shock",
    also: ["loaded strut", "quick strut", "damper"],
    means: "The damper. Leaking or failed rebound. Springs are separate unless they sell a loaded assembly.",
    sayToOwner: "Leak photo? Bounce test is weak evidence. Ask for the leak or the broken spring.",
    trap: "Four corners 'because we recommend in pairs' — pairs on an axle are fair; all four needs a reason.",
    group: "steering",
  },
  {
    slug: "tie-rod",
    term: "Tie rod (inner / outer)",
    also: ["end", "rack end"],
    means: "Steering link. Inner vs outer are different parts. Alignment after.",
    sayToOwner: "Which end, and is the boot torn? Alignment is part of the job.",
    trap: "Replacing outers and skipping the alignment is a tire bill.",
    group: "steering",
  },
  {
    slug: "rack",
    term: "Rack & pinion",
    also: ["steering rack", "eps rack"],
    means: "The steering gear. Leak at the boots or a dead EPS motor.",
    sayToOwner: "Photo of the leak. Is it the rack or a line? Alignment after.",
    trap: "A 'steering leak' can be a power-steering line. Confirm the wet part.",
    group: "steering",
  },
  {
    slug: "ac-recharge",
    term: "A/C recharge",
    also: ["evac recharge", "top off", "freon"],
    means: "Recover, evacuate, recharge to the gram. A leak test should be on the same ticket if it was low.",
    sayToOwner: "How many grams went in, and where was the leak? A top-off without a leak is a subscription.",
    trap: "Cans from the parts store on a hybrid/EV electric compressor can kill the compressor.",
    group: "hvac",
  },
  {
    slug: "induction",
    term: "Induction / fuel system service",
    also: ["throttle service", "sea foam", "decarbon"],
    means: "Clean intake or injectors. Fair on some GDI carbon jobs when they show the camera.",
    sayToOwner: "Show me the carbon or the misfire that this fixes. A bottle is not a camera.",
    trap: "Menu induction at every LOF is an upsell. Camera or a documented GDI interval is a reason.",
    group: "service",
  },
  {
    slug: "cabin-filter",
    term: "Cabin filter",
    also: ["pollen filter", "hvac filter"],
    means: "The filter behind the glove box (usually). Air you breathe.",
    sayToOwner: "Show me the old one. If it is white, I can decline.",
    trap: "A $90 cabin filter at the dealer is often a $15 part plus 0.2 hours. Ask to see it.",
    group: "service",
  },
  {
    slug: "tpms",
    term: "TPMS",
    also: ["tire pressure sensor", "relearn"],
    means: "Tire-pressure sensors. Service kits (stems) at every tire job are a shop habit; batteries die with age.",
    sayToOwner: "Which corner failed, and is it the sensor or a leak?",
    trap: "Four new sensors because one battery died is a parts cannon unless they are all 8–10 years old and you agree.",
    group: "tires",
  },
  {
    slug: "rotation",
    term: "Tire rotation",
    also: ["rotate and balance"],
    means: "Move tires to even the wear. Torque the lugs to the chart — not an impact-only snug.",
    sayToOwner: "Pattern (forward cross vs rearward) and lug torque. Ask them not to guess.",
    trap: "Rotation sold with an alignment you did not need. Wear pattern decides the alignment.",
    group: "tires",
  },
  {
    slug: "road-force",
    term: "Road-force balance",
    also: ["hunter road force"],
    means: "A balancer that loads the tire like the road. Finds a stiff spot a spin-balance misses.",
    sayToOwner: "Fair on a shake that survived a normal balance. Not automatic on every tire sale.",
    trap: "Road-force plus four new tires plus an alignment is a bundle. Split the complaint: shake vs pull.",
    group: "tires",
  },
  {
    slug: "timing-belt",
    term: "Timing belt vs chain",
    also: ["timing kit", "water pump kit"],
    means: "Belt is a service part with an interval. Chain is 'lifetime' until it stretches — then it is a job.",
    sayToOwner: "Belt or chain on this VIN? If belt, the water pump is usually 'while we're in there' with a price.",
    trap: "Calling a chain a belt to sell a kit. Identify first.",
    group: "service",
  },
  {
    slug: "water-pump",
    term: "Water pump",
    also: ["weep hole", "gasket"],
    means: "Moves coolant. Weep-hole crust or play is a fail. Not a thermostat.",
    sayToOwner: "Photo of the weep. Thermostat is a different part unless they price both.",
    trap: "A pump on every overheating ticket. Temp graph first (see P0128).",
    group: "service",
  },
  {
    slug: "diff-tcase",
    term: "Diff / transfer case service",
    also: ["differential", "t-case", "4wd service"],
    means: "Gear oil in axles and the transfer case. Interval or leak, not every oil change.",
    sayToOwner: "Which unit, which spec (GL-5, limited-slip additive), and did they find metal?",
    trap: "A '4x4 service package' without naming the units is a bundle.",
    group: "trans",
  },
  {
    slug: "cv-axle",
    term: "CV axle",
    also: ["halfshaft", "clicking on turn"],
    means: "The shaft with the rubber boot. Click on turn is the outer joint.",
    sayToOwner: "Which side, and is the boot torn or is it already clicking?",
    trap: "Two axles 'in pairs' when one boot is torn. The quiet side can wait if the boot is intact.",
    group: "steering",
  },
  {
    slug: "program",
    term: "Program / module",
    also: ["flash", "program keys", "bcm", "tcm", "ecm"],
    means: "Software or a control unit. Needs the right battery voltage and factory software.",
    sayToOwner: "New module or a reflash of the old one? TSB number?",
    trap: "A module because of a U-code. Read /jobs/obd — silent is often voltage.",
    group: "diag",
  },
  {
    slug: "nitrogen",
    term: "Nitrogen fill",
    also: ["n2"],
    means: "Air is already ~78% nitrogen. A paid fill is a F&I or service extra.",
    sayToOwner: "I can decline. PSI on the door sticker matters more than the gas blend.",
    trap: "Sold as if air were wrong. It is not required for the warranty.",
    group: "tires",
  },
  {
    slug: "out-of-spec",
    term: "Out of spec / close to spec",
    also: ["in spec", "minimum", "discard thickness"],
    means: "Compared to a published number. Close-to-spec is a judgment; below-minimum is a fail.",
    sayToOwner: "Write both numbers: measured and book. I decide close. You decide fail.",
    trap: "'Close' on a rotor that still machines above min is a sales word.",
    group: "ticket",
  },
];

export function searchRoTerms(query: string): RoTerm[] {
  const q = query.trim().toLowerCase();
  if (!q) return RO_TERMS;
  return RO_TERMS.filter((term) => {
    const blob = `${term.term} ${term.also.join(" ")} ${term.means} ${term.slug}`.toLowerCase();
    return blob.includes(q);
  });
}
