import type { TsbPattern } from "@/lib/expert/types";

const SAFER = "https://www.nhtsa.gov/recalls";

/** Pattern cards — not OEM TSB PDFs. Owned expert layer. */
export const EXTRA_TSB: TsbPattern[] = [
  {
    id: "honda-15t-dilution",
    stamp: "1.5T",
    symptom: "Oil smells like gas, rising oil level, or a misfire after short trips on a Honda 1.5T",
    makes: ["Honda", "Acura"],
    models: ["Civic", "CR-V", "Accord", "HR-V"],
    years: "2016+ 1.5 turbo (L15B7 / L15CA) — engine code decides",
    pattern:
      "Owners and SaferCar complaints describe fuel-diluted oil on some 1.5T Hondas after lots of cold short trips. The beginner move is a measured oil level and a smell test — not an automatic “needs a new engine.” Honda issued dealer information on some years. We will not paste it.",
    notATsb: "Complaint pattern plus public campaigns where they exist. Not a pirated Honda TIS PDF.",
    dummyMove: "Photo the dipstick on level ground. If it smells like fuel or it is over full, ask for a dilution test before anyone quotes a bottom end.",
    geniusNote:
      "A quart high after a week of 3-mile trips is a number. “They all do that” is not. Confirm 1.5T vs 2.0 on the under-hood label.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["oil-spec", "check-engine", "pre-shop"],
  },
  {
    id: "honda-cvt-start-clutch",
    stamp: "HCF-2",
    symptom: "Honda CVT shudder, flare, or a “transmission flush” quote on a CR-V / Civic / Accord 1.5T",
    makes: ["Honda"],
    models: ["CR-V", "Civic", "Accord", "HR-V", "Fit"],
    years: "2014+ CVT with HCF-2",
    pattern:
      "HCF-2 is not Dexron. Public owner files and shop-forum consensus: a lube-shop flush with generic ATF is a damage path. Start-clutch or converter shudder is a diagnosis, not a $189 special.",
    notATsb: "Pattern card. If a dealer cites a bulletin, they show the Honda number. We do not host it.",
    dummyMove: "Ask them to write HCF-2 on the RO. Refuse a machine flush until they name the OEM procedure.",
    geniusNote: "10-speed Accords use DW-1, not HCF-2. Read the under-hood label before you buy a jug.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["trans-flush", "after-quote"],
  },
  {
    id: "honda-j35-vcm",
    stamp: "VCM",
    symptom: "Motor-mount thump, misfire on a Honda J35, or a “needs mounts and coils” quote together",
    makes: ["Honda", "Acura"],
    models: ["Odyssey", "Pilot", "Ridgeline", "Accord", "MDX"],
    years: "2008+ J35 with VCM (verify the engine, not the badge)",
    pattern:
      "Variable Cylinder Management on some J35s is a widely reported mount and plug-fouling story in public complaints. The first look is oil, plugs, and which cylinders are counting — not a four-mount package from a thump.",
    notATsb: "Owner-known pattern. Honda had software and mount campaigns on some VINs. We will not reproduce the PDF.",
    dummyMove: "Record the thump on a phone. Ask for misfire counts and a mount photo, one system at a time.",
    geniusNote: "A rear mount that is torn is a measurement (torn rubber). “They all thump” is not a parts list.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["misfire", "pre-shop"],
  },
  {
    id: "honda-accord-trans-03",
    stamp: "04 AT",
    symptom: "2nd-gear flare or a hard 1-2 on a 2003–2007 Honda Accord automatic",
    makes: ["Honda"],
    models: ["Accord"],
    years: "2003–2007 5-speed automatic (not the 6MT)",
    pattern:
      "This generation’s automatic is a well-known public complaint pile: flare, delay, and eventual failure if fluid is ignored. The fluid is ATF-Z1 / DW-1 — not Dexron. A power flush after it already slips is how you buy a box.",
    notATsb: "Complaint pattern. Honda had dealer programs on some years. We do not paste them. SaferCar plus a road test.",
    dummyMove: "Ask for a stall-speed / road-test note and the fluid name. Do not authorize a rebuild from a one-time flare without a test.",
    geniusNote: "The bay’s demo VIN is a 2003 Accord. Run Takata first. The transmission is a separate ticket.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["trans-flush", "used-ppi", "history-jacket"],
  },
  {
    id: "gm-afm-lifter",
    stamp: "AFM",
    symptom: "Tick on a GM 5.3/6.2, misfire after a hot soak, or an “AFM delete” quote on the first visit",
    makes: ["Chevrolet", "GMC", "Cadillac"],
    models: ["Silverado", "Sierra", "Tahoe", "Suburban", "Yukon", "Escalade"],
    years: "2007+ AFM / DFM V8 (LC9, L83, L84, L87 — VIN / RPO decides)",
    pattern:
      "Active Fuel Management lifter collapse is a widely filed SaferCar and owner pattern on some EcoTec3 and earlier 5.3s. The first visit is a stethoscope, oil level, and which hole is counting — not an automatic long-block.",
    notATsb: "Complaint pattern. GM issued bulletins and campaigns on some lifters. We will not reproduce them.",
    dummyMove: "Ask for a cold-vs-hot recording and misfire counts. “Needs a new engine” on visit one is a pause, not a yes.",
    geniusNote: "AFM delete is an aftermarket conversation, not a factory recall. Warranty and campaign paths are VIN-specific on SaferCar.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["misfire", "used-ppi", "check-engine"],
  },
  {
    id: "gm-dexcool-intake",
    stamp: "Dex-Cool",
    symptom: "Coolant loss, sweet smell, or a “flush special” on a GM V6/V8 with Dex-Cool",
    makes: ["Chevrolet", "GMC", "Buick", "Cadillac"],
    models: ["Many — intake / water-pump / Dex-Cool era"],
    years: "1996+ Dex-Cool (plastic intake and later EcoTec3 still apply)",
    pattern:
      "Dex-Cool is a chemistry, not a color. Public files include intake-gasket seepage on older 3.1/3.4/3.8 and later thermostat-housing leaks (Cruze 1.4T). A flush does not seal a housing.",
    notATsb: "Pattern card. We do not host GM TIS. If they cite a bulletin, they show the number and the leak.",
    dummyMove: "Pressure-test before a flush. Photo the leak. Refuse universal green in a Dex-Cool car.",
    geniusNote: "Cruze 1.4T coolant at the thermostat housing is a diagnosis. Equinox 2.4 timing-chain slack is a different ticket.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["coolant-spec", "after-quote"],
  },
  {
    id: "ford-ecoboost-coolant",
    stamp: "EB cool",
    symptom: "Ford EcoBoost eating coolant, white residue on the degas cap, or a “head gasket” quote with no test",
    makes: ["Ford", "Lincoln"],
    models: ["Escape", "Fusion", "Explorer", "Edge", "F-150", "Mustang", "Expedition"],
    years: "2010+ 1.5 / 1.6 / 2.0 / 2.3 / 2.7 / 3.5 EcoBoost — displacement decides",
    pattern:
      "Several EcoBoost families have public coolant-loss piles (degas bottle, oil cooler, block issues on some 1.5/1.6). The beginner move is a measured loss and a pressure test — not a head-gasket package from a smell.",
    notATsb: "SaferCar complaints and public investigations. Ford TSBs exist on some engines. We will not paste them.",
    dummyMove: "Mark the bottle, drive 200 miles, photo the level. Ask for a cooling-system pressure test before a teardown.",
    geniusNote: "1.5 vs 2.0 vs 3.5 are different tickets. Read the under-hood label. A 3.5 F-150 is not a 1.5 Escape.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["coolant-spec", "used-ppi", "check-engine"],
  },
  {
    id: "ford-dps6",
    stamp: "DPS6",
    symptom: "Ford Focus / Fiesta shudder, no-move, or a “transmission flush” on a dry dual-clutch",
    makes: ["Ford"],
    models: ["Focus", "Fiesta"],
    years: "2012–2018 DPS6 / Powershift",
    pattern:
      "The DPS6 is a dry clutch, not a fluid-service automatic. Public complaints, lawsuits, and campaigns exist. A Dexron flush is the wrong job. Clutches and the TCM are the conversation — VIN on SaferCar for open campaigns.",
    notATsb: "Public campaign / complaint pattern. We do not host Ford TSB PDFs.",
    dummyMove: "Ask whether they are quoting clutches, a TCM, or a “flush.” Refuse the flush. Check SaferCar for this VIN.",
    geniusNote: "If the car is in the campaign population, that is a dealer path. An indie can still diagnose. They cannot invent ATF in a dry box.",
    nhtsaKind: "campaign",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["trans-flush", "lemon-buyback", "recall-first"],
  },
  {
    id: "ford-10r80",
    stamp: "10R80",
    symptom: "Ford 10-speed shudder, harsh 2–3, or “needs a flush with Mercon LV”",
    makes: ["Ford"],
    models: ["F-150", "Mustang", "Expedition", "Ranger", "Explorer", "Bronco"],
    years: "2017+ 10R80 (tag on the case)",
    pattern:
      "10R80 often wants Mercon ULV, not LV. Public shudder complaints exist. A wrong-fluid service is a valve-body path. The tag on the pan wins — not a poster.",
    notATsb: "Pattern card. Ford has dealer fluid and adaptive-relearn notes. We will not reproduce them.",
    dummyMove: "Photo the transmission tag. Ask ULV vs LV before anyone puts a hose on the cooler.",
    geniusNote: "A relearn after a fluid service is a procedure, not a hope. If they cannot name the fluid, walk.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["trans-flush", "after-quote"],
  },
  {
    id: "hyundai-theta",
    stamp: "Theta",
    symptom: "Knock, rod bearing, or a seized Hyundai/Kia 2.0 / 2.4 GDI — or a bottom-end quote without a campaign check",
    makes: ["Hyundai", "Kia"],
    models: ["Sonata", "Santa Fe", "Tucson", "Optima", "Sorento", "Sportage", "Forte"],
    years: "Theta II 2.0T / 2.4 — roughly 2011–2019 (VIN decides)",
    pattern:
      "Theta II engines have a large public SaferCar and campaign history. The first move is VIN on SaferCar and the open engine campaigns — not a Facebook rebuild. Knock sensors and oil-change records matter on some programs.",
    notATsb: "Public campaigns and complaints. We will not paste Hyundai TSB text or serial lists.",
    dummyMove: "Run the VIN at SaferCar before you authorize a short-block. Ask what campaign is open on this VIN.",
    geniusNote: "A well-maintained Theta can still be in a campaign. A neglected one can be out of a program. The VIN page is the file.",
    nhtsaKind: "campaign",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["recall-first", "used-ppi", "check-engine"],
  },
  {
    id: "toyota-hybrid-inverter",
    stamp: "Inverter",
    symptom: "Toyota/Lexus hybrid Ready light, inverter coolant warning, or a “needs a hybrid battery” quote from a 12V test",
    makes: ["Toyota", "Lexus"],
    models: ["Prius", "Camry", "RAV4", "Highlander", "Sienna", "RX", "ES"],
    years: "2004+ hybrids — generation decides",
    pattern:
      "Inverter / transaxle coolant is a separate loop from the engine on many Toyotas. A 12V that is down will also refuse Ready. Public files mix pack quotes with 12V and inverter-pump failures. Measure first.",
    notATsb: "Pattern card. Toyota had inverter-cooler and pump campaigns on some years. VIN on SaferCar. No PDF here.",
    dummyMove: "Check 12V rested voltage and inverter-coolant level before anyone prices a pack.",
    geniusNote: "A 2010–15 Prius inverter coolant bottle is not the engine overflow. Two caps. Two chemistries sometimes.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["ev-12v", "coolant-spec", "check-engine"],
  },
  {
    id: "mazda-carbon",
    stamp: "GDI",
    symptom: "Cold idle stumble or a “needs walnut blast” quote on a Mazda Skyactiv-G with no misfire counts",
    makes: ["Mazda"],
    models: ["CX-5", "Mazda3", "Mazda6", "CX-30", "CX-50"],
    years: "2012+ Skyactiv-G GDI",
    pattern:
      "Direct-injection intake valves can grow carbon. That is a real service on many GDI engines — and also a popular upsell. The beginner move is misfire counts, fuel trims, and a borescope photo, not a $600 blast from a stumble once.",
    notATsb: "Industry pattern, not a stolen Mazda TSB. If they cite one, they show the number and the photo.",
    dummyMove: "Ask for a borescope still of the valves and which cylinders are counting. One stumble is not a blast.",
    geniusNote: "Skyactiv-T (turbo) plug gap is not the NA 0.051 in card. Confirm the engine before you buy plugs.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["misfire", "check-engine"],
  },
  {
    id: "jeep-9speed",
    stamp: "948TE",
    symptom: "Jeep Cherokee / Compass 9-speed harsh shifts or a Dexron flush quote",
    makes: ["Jeep", "Ram"],
    models: ["Cherokee", "Compass", "Renegade"],
    years: "2014+ 948TE / 9-speed",
    pattern:
      "The 9-speed wants the 8&9 Speed ATF, not ATF+4 and not Dexron. Public complaint piles on harsh 1–2 and software. A flush with the wrong jug is a valve-body bill.",
    notATsb: "Complaint pattern. FCA software TSBs exist. We will not host them. Ask them to show the number.",
    dummyMove: "Write 8&9 Speed ATF on the RO. Check SaferCar for TCM/software campaigns on this VIN.",
    geniusNote: "A relearn after fluid or a battery disconnect is a procedure. If they cannot name it, do not let them “adapt it with a drive.”",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["trans-flush", "after-quote"],
  },
  {
    id: "tesla-lv-battery",
    stamp: "LV",
    symptom: "Tesla or late EV that is silent, 12V / LV warning, or a pack quote from a dark screen",
    makes: ["Tesla", "Many"],
    models: ["Model 3", "Model Y", "Model S", "Model X", "Other HV cars"],
    years: "2012+",
    pattern:
      "The low-voltage battery still wakes the car. Public owner files are full of pack quotes that were a 12V/LV. Some refreshes moved to a lithium 16V. The measurement is voltage and a load test — not a mobile-app guess.",
    notATsb: "Pattern card. Tesla service bulletins are not ours to republish. SaferCar still takes complaints.",
    dummyMove: "Rested LV voltage first. Jump only at the approved points. Flatbed if it will not wake.",
    geniusNote: "A cabin-filter HEPA job is not an oil change. A shop that quotes 0W-20 on a Model 3 has the wrong VIN.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["ev-12v", "ev-owner"],
  },
  {
    id: "nissan-qr25-oil",
    stamp: "QR25",
    symptom: "Nissan 2.5 uses oil, or a misfire after the stick was ignored",
    makes: ["Nissan", "INFINITI"],
    models: ["Altima", "Rogue", "Sentra", "Frontier"],
    years: "QR25 / PR25 — 2000s–2020s (engine code decides)",
    pattern:
      "Some QR25 families have public oil-consumption complaints. The beginner move is quarts per 1,000 miles on level ground — same discipline as the Toyota 2AZ card. A PCV and a hope is not a complete diagnosis.",
    notATsb: "Complaint pattern. Nissan may have dealer notes on some VINs. We will not paste them.",
    dummyMove: "Fill to the stick, write the miles, recheck in 1,000. Photo the stick. Then talk parts.",
    geniusNote: "NS-3 in the CVT is a different ticket. Do not let a consumption test turn into a Dexron flush.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["oil-spec", "used-ppi", "road-trip"],
  },
  {
    id: "subaru-fb-oil",
    stamp: "FB oil",
    symptom: "Subaru FB/FA oil consumption or a cold start rattle on 0W-20 vs 5W-30 confusion",
    makes: ["Subaru"],
    models: ["Outback", "Forester", "Impreza", "Crosstrek", "WRX"],
    years: "2011+ FB20 / FB25 / FA20 — turbo years often different",
    pattern:
      "FB boxers have public consumption and head-gasket-adjacent piles depending on year. WRX FA20DIT US spec is often 5W-30 — a 0W-20 Outback habit is the wrong ticket. Cap wins.",
    notATsb: "Pattern card. Subaru TSBs on consumption exist for some VINs. SaferCar plus a measured log. No PDF here.",
    dummyMove: "Read the cap. Log quarts per 1,000. Do not copy an Outback 0W-20 onto a WRX.",
    geniusNote: "CVT fluid is still a Subaru SKU. A consumption test does not authorize a Dexron flush.",
    nhtsaKind: "complaint-pattern",
    saferCarUrl: SAFER,
    vinLookupUrl: SAFER,
    relatedPlaybooks: ["oil-spec", "trans-flush"],
  },
];
