import type { IntegrationAction, IntegrationContext, IntegrationDef } from "@/lib/integrations/types";
import {
  advanceUrl,
  amazonUrl,
  appleMapsDirUrl,
  autozoneUrl,
  batUrl,
  carfaxUrl,
  carsBidsUrl,
  copartUrl,
  directoryUrl,
  ebayMotorsUrl,
  epaFindACarUrl,
  fuellyUrl,
  googleMapsDirUrl,
  iaaUrl,
  iihsRatingsUrl,
  nominatimUrl,
  nhtsaComplaintsUrl,
  nhtsaRecallsUrl,
  nhtsaVehicleUrl,
  nhtsaVinDecoderUrl,
  oreillyUrl,
  repairPalUrl,
  rockautoUrl,
  yelpShopUrl,
  youtubeHowToUrl,
} from "@/lib/integrations/urls";

export const ENV_KEYS = [
  "OPENAI_API_KEY",
  "GOOGLE_PLACES_API_KEY",
  "YELP_API_KEY",
  "YOUTUBE_API_KEY",
  "CARSXE_API_KEY",
  "MARKETCHECK_API_KEY",
  "VINAUDIT_API_KEY",
] as const;

export const INTEGRATIONS: IntegrationDef[] = [
  {
    id: "nhtsa-vpic",
    stamp: "vPIC",
    name: "NHTSA VIN decoder",
    family: "safety",
    lane: "live",
    dummy: "The 17 characters in the corner of the windshield tell the factory what this car is. Open the official decoder — we do not invent a plate-to-VIN lookup.",
    genius: "vPIC is manufacturer 565 data. Decode here with the public API, then confirm campaigns on SaferCar. A clone VIN still decodes; a title brand does not appear.",
    homeUrl: "https://vpic.nhtsa.dot.gov/decoder",
    href: () => nhtsaVinDecoderUrl(),
    appPath: "/",
    tool: "vin",
  },
  {
    id: "nhtsa-safercar",
    stamp: "SaferCar",
    name: "NHTSA recalls",
    family: "safety",
    lane: "live",
    dummy: "Type the VIN on NHTSA’s recall desk. If a campaign is open, the dealer fixes it for free. That is not a shop upsell.",
    genius: "SaferCar VIN lookup is the owner-facing campaign check. Year/make/model lists possible campaigns; only the VIN tells you if yours is still open. We also call api.nhtsa.gov.",
    homeUrl: "https://www.nhtsa.gov/recalls",
    href: nhtsaRecallsUrl,
    appPath: "/recalls",
    tool: "recalls",
  },
  {
    id: "nhtsa-ncap",
    stamp: "NCAP",
    name: "NHTSA 5-star ratings",
    family: "safety",
    lane: "live",
    dummy: "Government crash stars for this year, make, and model. Not a dealer brochure.",
    genius: "NCAP overall / front / side / rollover come from api.nhtsa.gov SafetyRatings. Stars are for a tested variant — a different cab or airbag pack can change the row.",
    homeUrl: "https://www.nhtsa.gov/ratings",
    href: nhtsaVehicleUrl,
  },
  {
    id: "nhtsa-complaints",
    stamp: "ODI",
    name: "SaferCar complaints",
    family: "safety",
    lane: "live",
    dummy: "What other owners already filed on this nameplate. A pile of complaints is a question, not a diagnosis.",
    genius: "ODI complaints are owner narratives. Count + crash/fire flags are useful. They are not a statistically controlled failure rate and they are not a Carfax.",
    homeUrl: "https://www.nhtsa.gov/search",
    href: nhtsaComplaintsUrl,
  },
  {
    id: "epa-mpg",
    stamp: "EPA",
    name: "FuelEconomy.gov MPG",
    family: "fuel",
    lane: "live",
    dummy: "Official city / highway / combined MPG for this car. Not the number in a Facebook ad.",
    genius: "We walk year → make → model → options on the public REST menu, then /vehicle/{id}. Combined is comb08. Two transmissions are two rows — we do not average them.",
    homeUrl: "https://www.fueleconomy.gov/",
    href: epaFindACarUrl,
    tool: "mpg",
  },
  {
    id: "epa-findacar",
    stamp: "Find-a-Car",
    name: "FuelEconomy.gov Find-a-Car",
    family: "fuel",
    lane: "live",
    dummy: "The government Find-a-Car desk. Pick year and make the same way you would at the library computer.",
    genius: "PowerSearch is the official compare tool. Use it when you want side-by-side trims, not a single combined number.",
    homeUrl: "https://www.fueleconomy.gov/feg/findacar.shtml",
    href: epaFindACarUrl,
  },
  {
    id: "osm-nominatim",
    stamp: "OSM",
    name: "OpenStreetMap / Nominatim",
    family: "maps",
    lane: "live",
    dummy: "Type a ZIP. We pin it, then the directory shows rooftops nearby. We do not book a bay.",
    genius: "Nominatim geocodes (1 req/s, User-Agent required). Overpass draws shop=car_repair and friends. Public instances time out — the directory keeps demo ZIPs so the desk never dies empty.",
    homeUrl: "https://nominatim.openstreetmap.org/ui/search.html",
    href: nominatimUrl,
    appPath: "/directory",
    tool: "geocode",
  },
  {
    id: "youtube-howto",
    stamp: "How-to",
    name: "YouTube how-to",
    family: "video",
    lane: "live",
    dummy: "Search the job the way you would after the parts counter: “this car + cabin filter + how to.”",
    genius: "Search URLs always work. A YOUTUBE_API_KEY turns the related clip list on. We still will not invent a video ID we did not get back.",
    homeUrl: "https://www.youtube.com/results?search_query=cabin+filter+how+to",
    href: youtubeHowToUrl,
    appPath: "/guides",
    tool: "youtube",
  },
  {
    id: "rockauto",
    stamp: "Catalog",
    name: "RockAuto",
    family: "parts",
    lane: "live",
    dummy: "The catalog search you would type yourself. Confirm the application before you click buy.",
    genius: "Outbound catalog URL only. No aisle count, no interchange table. TecDoc is a paid license — this bay will not fake it.",
    homeUrl: "https://www.rockauto.com/en/catalog/",
    href: rockautoUrl,
    appPath: "/directory/parts",
  },
  {
    id: "autozone",
    stamp: "Retail",
    name: "AutoZone",
    family: "parts",
    lane: "live",
    dummy: "Retail search for the same SKU string. Still not a shelf-count.",
    genius: "searchresult?searchText= is a public storefront query. Loaner tools and warranty live on their site.",
    homeUrl: "https://www.autozone.com/",
    href: autozoneUrl,
  },
  {
    id: "advance",
    stamp: "Retail",
    name: "Advance Auto Parts",
    family: "parts",
    lane: "live",
    dummy: "Same query, different counter. Open their search. We do not know if the box is in the back.",
    genius: "Shop search URL. Their store finder is public. Inventory APIs are not something we will invent.",
    homeUrl: "https://shop.advanceautoparts.com/",
    href: advanceUrl,
  },
  {
    id: "oreilly",
    stamp: "Retail",
    name: "O’Reilly Auto Parts",
    family: "parts",
    lane: "live",
    dummy: "Parts plus loaner tools. Search opens on their site.",
    genius: "Public search. Loan-a-tool and interchange stay on oreillyauto.com. We do not scrape the counter.",
    homeUrl: "https://www.oreillyauto.com/",
    href: oreillyUrl,
  },
  {
    id: "amazon",
    stamp: "Market",
    name: "Amazon",
    family: "parts",
    lane: "live",
    dummy: "Marketplace search. Read the fitment notes. A five-star listing can still be the wrong filter.",
    genius: "s?k= query only. No Buy Box scrape, no “in stock at your dealer.”",
    homeUrl: "https://www.amazon.com/",
    href: amazonUrl,
  },
  {
    id: "ebay-motors",
    stamp: "Used",
    name: "eBay Motors",
    family: "parts",
    lane: "live",
    dummy: "Used and aftermarket. Category 6000 is Motors. Browse, then check seller notes.",
    genius: "The Browse API needs a client secret. This line is a search URL. Request the API separately if you want listings in-app.",
    homeUrl: "https://www.ebay.com/sch/6000/i.html",
    href: ebayMotorsUrl,
  },
  {
    id: "google-maps",
    stamp: "Drive",
    name: "Google Maps directions",
    family: "maps",
    lane: "live",
    dummy: "Paste the shop address. This opens turn-by-turn — the same link you would text a ride.",
    genius: "maps/dir/?api=1&destination= is the official directions deep link. We do not embed a billed Maps session unless GOOGLE_PLACES_API_KEY is set for rooftops.",
    homeUrl: "https://www.google.com/maps",
    href: googleMapsDirUrl,
    tool: "maps",
  },
  {
    id: "apple-maps",
    stamp: "Drive",
    name: "Apple Maps directions",
    family: "maps",
    lane: "live",
    dummy: "Same address, Apple Maps. On an iPhone this is the blue app, not a web maze.",
    genius: "maps.apple.com/?daddr= hands off to the Maps app when present, or the web fallback. No key. No tracking pixel.",
    homeUrl: "https://maps.apple.com/",
    href: appleMapsDirUrl,
    tool: "maps",
  },
  {
    id: "iihs",
    stamp: "IIHS",
    name: "IIHS ratings",
    family: "safety",
    lane: "live",
    dummy: "Insurance Institute crash tests. Their ratings page is the lookup — type the car there.",
    genius: "IIHS pages are body-style specific (sedan vs hatch). We will not guess civic-4-door-sedan. Open their official ratings desk.",
    homeUrl: "https://www.iihs.org/ratings",
    href: () => iihsRatingsUrl(),
  },
  {
    id: "carfax-consumer",
    stamp: "History",
    name: "Carfax consumer",
    family: "history",
    lane: "live",
    dummy: "The public report desk. Buy a report from them if you need one. We do not scrape Carfax.",
    genius: "Consumer portal only — type the VIN on their report desk. There is no free Carfax API we are allowed to republish.",
    homeUrl: "https://www.carfax.com/vehicle-history-reports/",
    href: () => carfaxUrl(),
  },
  {
    id: "repairpal",
    stamp: "Shops",
    name: "RepairPal",
    family: "shops",
    lane: "live",
    dummy: "Shop research and a ballpark estimator. They rate shops. We do not.",
    genius: "Link-out. RepairPal is a marketplace with certified shops. Open Hood will not book or take a cut. Use them as a second opinion, not as our network.",
    homeUrl: "https://repairpal.com/estimator",
    href: repairPalUrl,
  },
  {
    id: "yelp-research",
    stamp: "Reviews",
    name: "Yelp shop research",
    family: "shops",
    lane: "live",
    dummy: "Search auto repair near the ZIP. Read the fights in the reviews. We do not certify anyone.",
    genius: "Public search URL. A YELP_API_KEY merges Fusion rooftops into /directory. Stars we did not fetch will not be invented.",
    homeUrl: "https://www.yelp.com/search?find_desc=auto+repair",
    href: yelpShopUrl,
    appPath: "/directory",
  },
  {
    id: "fuelly",
    stamp: "Owner MPG",
    name: "Fuelly",
    family: "fuel",
    lane: "live",
    dummy: "What owners actually log at the pump. Optional. EPA is still the official number.",
    genius: "Fuelly is crowd-logged fill-ups. Useful as a sanity check against comb08. Not a lab test. We link the car page; we do not scrape tanks.",
    homeUrl: "https://www.fuelly.com/",
    href: fuellyUrl,
  },
  {
    id: "bring-a-trailer",
    stamp: "Public",
    name: "Bring a Trailer",
    family: "auctions",
    lane: "live",
    dummy: "Watch enthusiast auctions without a dealer plate. Bid with a free account if you want.",
    genius: "Public consumer lane. Search is ?s=. We do not scrape sold prices. This is the opposite of a Copart lot.",
    homeUrl: "https://bringatrailer.com/",
    href: batUrl,
    appPath: "/auctions",
  },
  {
    id: "cars-bids",
    stamp: "Public",
    name: "Cars & Bids",
    family: "auctions",
    lane: "live",
    dummy: "Modern cars, public listings. Same rule: watch for free, bid with their account.",
    genius: "Public consumer auction. search?q= year/make/model. No wholesale license.",
    homeUrl: "https://carsandbids.com/",
    href: carsBidsUrl,
    appPath: "/auctions",
  },
  {
    id: "copart",
    stamp: "Salvage",
    name: "Copart public search",
    family: "auctions",
    lane: "live",
    dummy: "Anyone can browse lots. Bidding is usually a dealer, dismantler, or a broker who charges you.",
    genius: "Public search URL only. We do not harvest lots, photos, or current bids. As-is. Buyer fees are real money.",
    homeUrl: "https://www.copart.com/",
    href: copartUrl,
    appPath: "/auctions",
  },
  {
    id: "iaa",
    stamp: "Salvage",
    name: "IAA public search",
    family: "auctions",
    lane: "live",
    dummy: "The other insurance salvage lane. Browse is public. The gavel usually is not.",
    genius: "Link-out Search?search=. Same honesty as Copart: no scrape, no fake “you can bid from this bay.”",
    homeUrl: "https://www.iaai.com/",
    href: iaaUrl,
    appPath: "/auctions",
  },
  {
    id: "openai",
    stamp: "Photos",
    name: "Photo reading",
    family: "licensed",
    lane: "env",
    env: "OPENAI_API_KEY",
    dummy: "When this key is on, a ticket or door-jamb photo uses the bay reader first. Without it, VIN decode and on-device reading still work.",
    genius: "Optional photo key on → POST /api/ocr is the first path for VIN and quote photos. Missing key → honest fallback, reading on this device. Never a dead button.",
    homeUrl: "https://platform.openai.com/api-keys",
    connectUrl: "https://platform.openai.com/api-keys",
    appPath: "/agent",
    href: () => "https://platform.openai.com/api-keys",
  },
  {
    id: "google-places",
    stamp: "Places",
    name: "Google Places",
    family: "maps",
    lane: "env",
    env: "GOOGLE_PLACES_API_KEY",
    dummy: "Denser rooftops than OpenStreetMap. Paid after the trial credit. Not required to use the directory.",
    genius: "Nearby Search (New) merges into /directory when the key exists. We do not scrape Maps HTML. No key → OSM + chain locators only, and we say so.",
    homeUrl: "https://console.cloud.google.com/google/maps-apis/api-list",
    connectUrl: "https://console.cloud.google.com/google/maps-apis/api-list",
    appPath: "/directory",
    href: directoryUrl,
  },
  {
    id: "yelp-fusion",
    stamp: "Fusion",
    name: "Yelp Fusion API",
    family: "shops",
    lane: "env",
    env: "YELP_API_KEY",
    dummy: "Optional phone / address merge for the directory. The public Yelp search link still works without it.",
    genius: "Bearer key → /v3/businesses/search. We will not invent star ratings. Without the key, use the Yelp research card.",
    homeUrl: "https://www.yelp.com/developers/v3/manage_app",
    connectUrl: "https://www.yelp.com/developers/v3/manage_app",
    appPath: "/directory",
    href: yelpShopUrl,
  },
  {
    id: "youtube-data",
    stamp: "Data API",
    name: "YouTube Data API",
    family: "video",
    lane: "env",
    env: "YOUTUBE_API_KEY",
    dummy: "Optional. How-to search links work with no key. This key lists related clips instead of only a results page.",
    genius: "Quota-based search.list. We refuse to hardcode a video we did not receive. Guides stay honest either way.",
    homeUrl: "https://console.cloud.google.com/apis/library/youtube.googleapis.com",
    connectUrl: "https://console.cloud.google.com/apis/library/youtube.googleapis.com",
    appPath: "/guides",
    href: youtubeHowToUrl,
  },
  {
    id: "tecdoc",
    stamp: "License",
    name: "TecDoc / TecAlliance",
    family: "licensed",
    lane: "catalog",
    env: "TECALLIANCE_KEY",
    dummy: "The OEM-linked parts catalog shops pay for. We do not fake interchange or labor hours.",
    genius: "Paid TecAlliance license. Until a key exists, the parts desk is outbound search URLs. Request access from TecAlliance — do not expect a free SKU dump.",
    homeUrl: "https://www.tecalliance.net/",
    connectUrl: "https://www.tecalliance.net/en/contact/",
    href: () => "https://www.tecalliance.net/en/contact/",
  },
  {
    id: "carfax-api",
    stamp: "License",
    name: "Carfax business API",
    family: "history",
    lane: "catalog",
    dummy: "Dealer / partner history API. Not the consumer report page. We will not scrape Carfax HTML.",
    genius: "There is no public free Carfax API. Partners go through Carfax for Dealers. The consumer card above is the honest owner path.",
    homeUrl: "https://www.carfaxfordealers.com/",
    connectUrl: "https://www.carfaxfordealers.com/",
    href: () => "https://www.carfaxfordealers.com/",
  },
  {
    id: "chrome-data",
    stamp: "OEM",
    name: "Chrome Data (J.D. Power)",
    family: "licensed",
    lane: "catalog",
    env: "CHROME_DATA_KEY",
    dummy: "Factory build data and style IDs. Enterprise contract. Not a weekend API key.",
    genius: "Licensed residual / style feed. Cataloged so we do not pretend NHTSA vPIC is Chrome. Request access from J.D. Power business.",
    homeUrl: "https://www.jdpower.com/business/automotive/chrome-data",
    connectUrl: "https://www.jdpower.com/business/automotive/chrome-data",
    href: () => "https://www.jdpower.com/business/automotive/chrome-data",
  },
  {
    id: "motor-identifix",
    stamp: "Shop",
    name: "MOTOR / Identifix",
    family: "licensed",
    lane: "catalog",
    env: "MOTOR_API_KEY",
    dummy: "Labor times and TSBs for shops. A paid subscription. Not a consumer free API.",
    genius: "Hearst Aftermarket. Hours in this bay stay heuristic until licensed. Request a shop login from MOTOR — we will not invent book time.",
    homeUrl: "https://www.motor.com/",
    connectUrl: "https://www.motor.com/",
    href: () => "https://www.motor.com/",
  },
  {
    id: "marketcheck",
    stamp: "Plate",
    name: "MarketCheck",
    family: "licensed",
    lane: "env",
    env: "MARKETCHECK_API_KEY",
    dummy: "Plate-to-VIN and listings. Paid after a small eval. No fake “in stock” tiles without a key.",
    genius: "Plate decoder is coded on /history. Listings stay catalog-only until we call their inventory API on purpose. No dealer HTML scrape.",
    homeUrl: "https://www.marketcheck.com/",
    connectUrl: "https://www.marketcheck.com/",
    appPath: "/history",
    href: () => "https://www.marketcheck.com/",
  },
  {
    id: "carsxe",
    stamp: "Plate",
    name: "CarsXE",
    family: "licensed",
    lane: "env",
    env: "CARSXE_API_KEY",
    dummy: "Plate-to-VIN. Paid per call. Without the key a plate is still a note. We do not invent a DMV lookup.",
    genius: "Code is in /history (POST /api/history/plate). Key on → decode. Key off → Connect. State restrictions apply. VIN path stays NHTSA.",
    homeUrl: "https://api.carsxe.com/",
    connectUrl: "https://api.carsxe.com/",
    appPath: "/history",
    href: () => "https://api.carsxe.com/",
  },
  {
    id: "vinaudit",
    stamp: "Title",
    name: "VinAudit",
    family: "history",
    lane: "env",
    env: "VINAUDIT_API_KEY",
    dummy: "Title brands, theft, salvage. Paid per report. Missing key → outbound Carfax / AutoCheck cards. We will not fake a Carfax.",
    genius: "Key on → /history title snapshot names VinAudit. Off → Connect. Never invents wrecks or a Carfax XML.",
    homeUrl: "https://www.vinaudit.com/",
    connectUrl: "https://www.vinaudit.com/api",
    appPath: "/history",
    href: () => "https://www.vinaudit.com/api",
  },
  {
    id: "autodev",
    stamp: "Listings",
    name: "Auto.dev",
    family: "licensed",
    lane: "catalog",
    env: "AUTODEV_API_KEY",
    dummy: "Marketplace listings search. Paid. We do not scrape dealer sites while this stays dark.",
    genius: "Cataloged upgrade. Request access on auto.dev.",
    homeUrl: "https://www.auto.dev/",
    connectUrl: "https://www.auto.dev/",
    href: () => "https://www.auto.dev/",
  },
  {
    id: "carapi",
    stamp: "Catalog",
    name: "CarAPI",
    family: "licensed",
    lane: "catalog",
    env: "CARAPI_API_KEY",
    dummy: "Year / make / model / trim catalogs. Freemium, then paid. NHTSA already covers VIN identity.",
    genius: "Nice for trim trees. Not required for vPIC decode. Request a token at carapi.app.",
    homeUrl: "https://carapi.app/",
    connectUrl: "https://carapi.app/",
    href: () => "https://carapi.app/",
  },
  {
    id: "ebay-browse",
    stamp: "OAuth",
    name: "eBay Browse API",
    family: "licensed",
    lane: "catalog",
    env: "EBAY_CLIENT_ID",
    dummy: "Live Motors listings need OAuth and a secret. The search URL on the eBay Motors card works today.",
    genius: "Browse is not a public key. Until a client secret exists, we will not pretend listings are in this bay.",
    homeUrl: "https://developer.ebay.com/",
    connectUrl: "https://developer.ebay.com/",
    href: () => "https://developer.ebay.com/",
  },
  {
    id: "mitchell",
    stamp: "Hours",
    name: "Mitchell / ProDemand",
    family: "licensed",
    lane: "catalog",
    env: "MITCHELL_API_KEY",
    dummy: "Shop labor times and estimating. Paid. We will not invent book hours and stamp them Mitchell.",
    genius: "Enterprise extract or shop subscription. Request access from Mitchell. /estimate stays a ZIP band until a signed feed exists.",
    homeUrl: "https://www.mitchell.com/",
    connectUrl: "https://www.mitchell.com/contact-us",
    href: () => "https://www.mitchell.com/contact-us",
  },
  {
    id: "alldata",
    stamp: "Hours",
    name: "ALLDATA",
    family: "licensed",
    lane: "catalog",
    env: "ALLDATA_API_KEY",
    dummy: "Shop service information. Subscription, rarely a public API. We do not scrape their manuals.",
    genius: "If they will not sell a feed, this jack stays Request access. Heuristic hours are not ALLDATA.",
    homeUrl: "https://www.alldata.com/",
    connectUrl: "https://www.alldata.com/us/en/contact",
    href: () => "https://www.alldata.com/us/en/contact",
  },
  {
    id: "cox-kbb",
    stamp: "Value",
    name: "Cox / KBB valuation",
    family: "licensed",
    lane: "catalog",
    env: "KBB_API_KEY",
    dummy: "Licensed residual / auction comps. /value is an illustration plus consumer search URLs until this feed is live.",
    genius: "Cox Automotive / KBB business API. A key that only flips a label is not a residual. Do not invent a number we did not fetch.",
    homeUrl: "https://www.coxautoinc.com/",
    connectUrl: "https://www.coxautoinc.com/contact/",
    appPath: "/value",
    href: () => "https://www.coxautoinc.com/contact/",
  },
  {
    id: "nmvtis-provider",
    stamp: "Title",
    name: "NMVTIS approved provider",
    family: "history",
    lane: "catalog",
    env: "NMVTIS_PROVIDER_KEY",
    dummy: "Federal title brands. Only an AAMVA-approved provider may sell the snapshot. We link the consumer pages today.",
    genius: "VinAudit, AutoCheck, or another approved reseller. We will not scrape NMVTIS HTML. Request a commercial agreement.",
    homeUrl: "https://vehiclehistory.bja.ojp.gov/nmvtis_consumers",
    connectUrl: "https://vehiclehistory.bja.ojp.gov/nmvtis_consumers",
    appPath: "/history",
    href: () => "https://vehiclehistory.bja.ojp.gov/nmvtis_consumers",
  },
  {
    id: "stripe-escrow",
    stamp: "Hold",
    name: "Stripe live / escrow partner",
    family: "licensed",
    lane: "catalog",
    env: "STRIPE_SECRET_KEY",
    dummy: "Live card capture and true escrow are not this bay. Packet fee is the only money on this desk, and only with a test key or an existing Price ID. Shop cuts and marketplace stay refused.",
    genius: "Stripe is not escrow. sk_test_ opens print-packet Checkout. sk_live_ needs STRIPE_PACKET_PRICE_ID we already have. Counsel signs before anything else.",
    homeUrl: "https://dashboard.stripe.com/apikeys",
    connectUrl: "https://dashboard.stripe.com/apikeys",
    appPath: "/trust",
    href: () => "https://dashboard.stripe.com/apikeys",
  },
  {
    id: "insurance-fnol",
    stamp: "Claim",
    name: "Insurance FNOL (CCC / Mitchell / Verisk)",
    family: "licensed",
    lane: "catalog",
    env: "CCC_API_KEY",
    dummy: "Carrier first-notice-of-loss APIs. /trust is a photo list and FNOL links until a carrier or CCC contract exists.",
    genius: "Enterprise, 6–12 months. We do not invent a claim number. Request a partnership; do not scrape carrier portals.",
    homeUrl: "https://www.cccis.com/",
    connectUrl: "https://www.cccis.com/contact",
    appPath: "/trust",
    href: () => "https://www.cccis.com/contact",
  },
  {
    id: "dealer-dms",
    stamp: "DMS",
    name: "Dealer DMS (CDK / Reynolds / Tekion)",
    family: "licensed",
    lane: "catalog",
    dummy: "We do not write the dealer RO. 100% as advocate is a visit packet and their scheduler — not a shop OS.",
    genius: "Partner programs are 6–18 months and often refuse consumer apps. Decision: never sit in their bay. Optional read-only appointment API only if they offer it and legal signs.",
    homeUrl: "https://www.cdkglobal.com/",
    connectUrl: "https://www.cdkglobal.com/contact",
    appPath: "/book",
    href: () => "https://www.cdkglobal.com/contact",
  },
  {
    id: "partstech",
    stamp: "Parts",
    name: "PartsTech / shop parts book",
    family: "licensed",
    lane: "catalog",
    env: "PARTSTECH_API_KEY",
    dummy: "ZIP-real parts prices shops actually buy. Not a RockAuto search URL. Paid shop account. This bay stays empty — no dummy SKUs.",
    genius: "PartsTech shop parts book after a contract. Adapter returns connected:false, skus:[]. Request a shop API; do not scrape storefronts. OSM stays the shop map.",
    homeUrl: "https://www.partstech.com/",
    connectUrl: "https://www.partstech.com/contact",
    href: () => "https://www.partstech.com/contact",
  },
];

export function integrationById(id: string): IntegrationDef | undefined {
  return INTEGRATIONS.find((item) => item.id === id);
}

export function integrationsByLane(lane: IntegrationDef["lane"]): IntegrationDef[] {
  return INTEGRATIONS.filter((item) => item.lane === lane);
}

export function actionFor(
  def: IntegrationDef,
  ctx: IntegrationContext,
  configuredEnvs: Record<string, boolean>,
): IntegrationAction {
  if (def.lane === "env" && def.env) {
    const connected = Boolean(configuredEnvs[def.env]);
    return {
      label: connected ? "Open" : "Connect",
      href: connected ? (def.appPath ?? def.href(ctx)) : (def.connectUrl ?? def.homeUrl),
      connected,
    };
  }
  if (def.lane === "catalog") {
    return {
      label: "Request access",
      href: def.connectUrl ?? def.homeUrl,
      connected: null,
    };
  }
  return { label: "Open", href: def.href(ctx), connected: null };
}

export const FAMILY_LABEL: Record<IntegrationDef["family"], string> = {
  safety: "Safety",
  fuel: "Fuel",
  maps: "Maps / geo",
  parts: "Parts counters",
  shops: "Shop research",
  auctions: "Auction lanes",
  video: "How-to",
  history: "History",
  licensed: "Licensed hooks",
};

export const STRIP_IDS = [
  "nhtsa-safercar",
  "epa-findacar",
  "rockauto",
  "google-maps",
  "iihs",
  "youtube-howto",
] as const;
